DROP TABLE IF EXISTS ONLN_APPL_MNT_SCH;
CREATE TABLE ONLN_APPL_MNT_SCH 
(ONLN_APPL_MNT_SCH_ID INTEGER NOT NULL,
LAST_UPD_SYSUSR_ID CHAR(24) NOT NULL,	
LAST_UPD_TS TIMESTAMP NOT NULL,	
MMD_APPL_ID INTEGER NOT NULL,
ONLN_APMNT_PRCSS_TYP_CD INTEGER NOT NULL,
MNT_BGN_DT TIMESTAMP ,
MNT_BGN_TM CHAR(24) NOT NULL,
MNT_END_DT TIMESTAMP ,
MNT_END_TM CHAR(24) NOT NULL,
ONLN_APPL_MNT_FREQ_CD INTEGER NOT NULL,
ACTV_FLG CHAR(1) NOT NULL)